<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>XmlToDb.Core</RootNamespace>
    <AssemblyName>XmlToDb.Core</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="CardView.xslt" />
  </ItemGroup>

</Project>
